FROM 475911326710.dkr.ecr.ap-northeast-1.amazonaws.com/node:20.13.1-slim

WORKDIR /flink

RUN apt update -y

RUN apt install -y python-is-python3

ADD . /flink

RUN npm install

RUN npm run build

CMD ["/bin/sh", "-c", "npm run migration:run && npm run start"]
